# Stage 1
FROM node:14.15.3-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY Frontend/package.json /app
RUN npm install
COPY Frontend /app
RUN npm run build --prod
 
# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/dist /usr/share/nginx/html